Django/Practice/P_15/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/comments/', views.comment_create, name='comment_create'),
    path(
        '<int:article_pk>/comments/<int:comment_pk>/delete/',
        views.comment_delete,
        name='comment_delete',
    ),
    path('<int:article_pk>/likes/', views.likes, name='likes'),
    path('<int:article_pk>/comments/<int:comment_pk>/likes/', views.comments_likes, name='comments_likes'),
]

Django/Practice/P_15/articles/models.py
from django.db import models
from django.conf import settings


class Article(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')

    title = models.CharField(max_length=80)
    content = models.TextField(null=False)


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_comments')
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    content = models.TextField(null=False)

Django/Practice/P_15/articles/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Article, Comment
from .forms import ArticleForm, CommentForm


def index(request):
    articles = Article.objects.order_by('-pk')
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)


def detail(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    comments = article.comment_set.all()
    comment_form = CommentForm()
    context = {
        'article': article,
        'comments': comments,
        'comment_form': comment_form,
    }
    return render(request, 'articles/detail.html', context)


@login_required
def create(request):
    if request.method == "POST":
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            return redirect('articles:detail', article_pk=article.pk)

    else:
        form = ArticleForm()

    context = {
        'form': form,
    }

    return render(request, 'articles/create.html', context)

@login_required
def delete(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    if request.user == article.user:
        article.delete()
    return redirect('articles:index')


@login_required
def comment_create(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.user = request.user
        comment.article = article
        comment.save()

    return redirect('articles:detail', article.pk)


@login_required
def comment_delete(request, article_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.user == comment.user:
        comment.delete()

    return redirect('articles:detail', article_pk)

@login_required
def likes(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    if request.user in article.like_users.all():
        article.like_users.remove(request.user)
    else:
        article.like_users.add(request.user)
    return redirect('articles:index')

@login_required
def comments_likes(request, article_pk,comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.user in comment.like_users.all():
        comment.like_users.remove(request.user)
    else:
        comment.like_users.add(request.user)
    return redirect('articles:detail', article_pk)

Django/Practice/P_15/articles/templates/articles/detail.html
{% extends "base.html" %}
{% block content %}
  <div>
    <h3>DETAIL</h3>
    <p>게시글 작성자 -
      {{article.user}}</p>
    <p>
      게시글 번호 -
      {{article.pk}}
    </p>
    <p>
      게시글 제목 -
      {{article.title}}
    </p>
    <p>
      게시글 내용 -
      {{article.content}}
    </p>
    <a href="{% url 'articles:index' %}">[back]</a>
    {% if request.user == article.user %}
    <form action="{% url 'articles:delete' article.pk  %}" method="POST">
      {% csrf_token %}
      <input type="submit" value="삭제">
    </form>
    {% endif %}
  </div>
  <hr>
  <form action="{% url 'articles:comment_create' article.pk %}" method="post">
    {% csrf_token %}
    {{ comment_form.as_p }}
    <input type="submit" value="댓글 작성">
  </form>
  <p>댓글 수 : {{ article.comment_set.all|length}}</p>
  <hr>

  {% for comment in comments %}
    <div>
      <p>댓글 작성자 -
        {{comment.user}}</p>
      <p>댓글 번호 -
        {{ comment.pk }}</p>
      <p>
        댓글 내용 -
        {{comment.content}}
      </p>

      {% if comment.user == user %}
        <form action="{% url 'articles:comment_delete' article.pk comment.pk %}" method="POST">
          {% csrf_token %}
          <input type="submit" value="댓글 삭제">
        </form>
      {% endif %}
      <form action="{% url 'articles:comments_likes' article.pk comment.pk %}" method="POST">
        {% csrf_token %}
        {% if request.user in comment.like_users.all %}
          <input type="submit" value="좋아요 취소">
        {% else %}
          <input type="submit" value="좋아요">
        {% endif %}
      </form>
      <p>좋아요 수 : {{ comment.like_users.all|length }}</p>
    </div>
    <hr>
  {% endfor %}
{% endblock content %}

Django/Practice/P_15/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>INDEX</h1>
  <h3>{{ request.user }}</h3>
  {% if request.user.is_authenticated %}
    <div>
      <form action="{% url 'accounts:logout' %}" method="POST">
        {% csrf_token %}
        <p>
          <input type="submit" value="로그아웃" autocomplete="off">
        </p>
      </form>
      <a href="{% url 'articles:create' %}">[글 작성]</a>
    </div>
  {% else %}
    <div>
      <a href="{% url 'accounts:login' %}">[로그인]</a>
      <a href="{% url 'accounts:signup' %}">[회원가입]</a>
    </div>
  {% endif %}
  {% for article in articles %}
    <div>
      <p>게시글 번호 -
        {{ article.pk }}
      </p>
      <p>게시글 작성자 -
        {{article.user}}</p>
      <p>
    </div>
    <a href="{% url 'articles:detail' article.pk %}">[게시글 조회]</a>
    {% if request.user.is_authenticated %}
    <form action="{% url 'articles:likes' article.pk %}" method="POST">
      {% csrf_token %}
      {% if request.user in article.like_users.all %}
        <input type="submit" value="좋아요 취소">
      {% else %}
        <input type="submit" value="좋아요">
      {% endif %}
    </form>
    {% endif %}

    <hr>
  {% endfor %}
{%endblock content %}