Django/Project/PJ_1/accountbooks/urls.py
from django.urls import path
from . import views

app_name = 'accountbooks'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

Django/Project/PJ_1/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accountbooks/', include('accountbooks.urls')),
]

Django/Project/PJ_1/accountbooks/models.py
from django.db import models

# Create your models here.

class AccountBook(models.Model):
    note = models.CharField(max_length=80)
    description = models.TextField(null=True)
    category = models.CharField(max_length=20)
    amount = models.IntegerField(default=0)
    date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

Django/Project/PJ_1/accountbooks/views.py
from django.shortcuts import render, redirect
from .models import AccountBook

# Create your views here.

def index(request):
    accountbooks = AccountBook.objects.all()
    context = {
        'accountbooks': accountbooks,
    }
    return render(request, 'accountbooks/index.html', context)

def detail(request, pk):
    accountbook = AccountBook.objects.get(pk=pk)
    context = {
        'accountbook': accountbook,
    }
    return render(request, 'accountbooks/detail.html', context)

def new(request):
    
    return render(request, 'accountbooks/new.html')
                  

def create(request):
    # 생성
    note = request.POST.get('note')
    description = request.POST.get('description')
    category = request.POST.get('category')
    amount = request.POST.get('amount')
    date = request.POST.get('date')
    
    # DB에 저장
    accountbook = AccountBook(note=note, description=description, category=category, amount=amount, date=date)
    accountbook.save()
    #결과 페이지 반환
    return redirect('accountbooks:detail', accountbook.pk)

def edit(request, pk):
    accountbook = AccountBook.objects.get(pk=pk)
    context = {
        'accountbook': accountbook,
    }
    return render(request, 'accountbooks/edit.html', context)


def update(request, pk):
    accountbook = AccountBook.objects.get(pk=pk)
    accountbook.note = request.POST.get('note')
    accountbook.description = request.POST.get('description')
    accountbook.category = request.POST.get('category')
    accountbook.amount = request.POST.get('amount')
    accountbook.date = request.POST.get('date')
    accountbook.save()

    return redirect("accountbooks:detail", accountbook.pk)

def delete(request, pk):
    accountbook = AccountBook.objects.get(pk=pk)
    accountbook.delete()
    return redirect('accountbooks:index')

Django/Project/PJ_1/accountbooks/templates/accountbooks/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <title>Document</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@300;400&family=Noto+Sans+KR:wght@500&display=swap" rel="stylesheet">
    {% block style %}{% endblock style %}
  </head>
  <style>
    body {
      font-family: 'Noto Sans JP', sans-serif;
      font-family: 'Noto Sans KR', sans-serif;
    }
    a {
      text-decoration: none;
    }
  </style>
  <body>
    {% block content %}

    {% endblock content %}


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
    crossorigin="anonymous"></script>
  </body>
</html>

Django/Project/PJ_1/accountbooks/templates/accountbooks/create.html
{% extends 'accountbooks/base.html' %}

{% block content %}
<h1>작성이 완료되었습니다.</h1>

<div class="container-fluid mt-5 d-flex justify-content-center">
    <a href="{% url 'accountbooks:index' %}" class="btn btn-outline-primary" role="button">돌아가기</a>
</div>
{% endblock content %}


Django/Project/PJ_1/accountbooks/templates/accountbooks/detail.html
{% extends 'accountbooks/base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="card mt-3 d-flex justify-content-center" style="width: 18rem;">
        <div class="card-header">
            <h1>{{accountbook.pk}} </h1>
        </div>
    <ul class="list-group list-group-flush">    
        <li class="list-group-item">
            <p>내용 - {{accountbook.note}}</p>
        </li>
        <li class="list-group-item">
            <p>메모 - {{accountbook.description}} </p>
        </li>
        <li class="list-group-item">
            <p>분류 - {{accountbook.category}}</p>
        </li>
        <li class="list-group-item">    
            <p>사용금액: {{accountbook.amount}}</p>
        </li>
        <li class="list-group-item">    
            <p>사용날짜: {{accountbook.date}}</p>
        </li>
    </ul>
    
    <a href="{% url 'accountbooks:edit' accountbook.pk%}" class="btn btn-outline-primary justify-align-center" style="width: 18rem;" role="button">수정하기</a>
    <a href="{% url 'accountbooks:index'%}" class="btn btn-outline-primary justify-align-center" style="width: 18rem;" role="button">메인 페이지</a>
    <form action="{% url 'accountbooks:delete' accountbook.pk %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="삭제하기" class="btn btn-outline-primary" role="button" style="width: 18rem;">
    </form>
    </div>
</div>

{% endblock content %}

Django/Project/PJ_1/accountbooks/templates/accountbooks/edit.html
{% extends 'accountbooks/base.html' %}

{% block content %}
<div class="container pt-5">
<header>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid d-flex justify-content-around">    
    <h1 class="">Edit &#x26A1;</h1>
    <a href="{% url 'accountbooks:index' %}" class="btn btn-outline-primary justify-align-center" role="button">메인 페이지</a>
    </div>
</nav>
</header>
<hr>
<main>
<form action="{% url 'accountbooks:update' accountbook.pk %}" method="POST">
    {% csrf_token %}
    <div class="input-group input-group-sm mb-3">
        <span class="input-group-text" id="inputGroup-sizing-sm" style="background-color: lightgoldenrodyellow;"> 내용 </span>
        <input type="text" name='note' id='note' class="form-control" value="{{accountbook.note}}">
    </div>
    <div class="input-group input-group-sm mb-3">
        <span class="input-group-text" id="inputGroup-sizing-sm" style="background-color: lightgoldenrodyellow;"> 분류 </span>
        <input type="text" name='category' id='category' class="form-control" value="{{accountbook.category}}">
    </div>
    <div class="input-group input-group-sm mb-3">
        <span class="input-group-text" id="inputGroup-sizing-sm" style="background-color: lightgoldenrodyellow;"> 사용금액 </span>
        <input type="text" name='amount' id='amount' class="form-control" value="{{accountbook.amount}}">
    </div>
    <div class="input-group input-group-sm mb-3">
        <span class="input-group-text" id="inputGroup-sizing-sm" style="background-color: lightgoldenrodyellow;"> 사용날짜 </span>
        <input type="date" name='date' id='date' class="form-control" value="{{accountbook.date}}" onchange="validDate" required>
    </div>
    <div class="input-group input-group-sm mb-3">
        <span class="input-group-text" id="inputGroup-sizing-sm" style="background-color: lightgoldenrodyellow;"> 메모 </span>
        <textarea class="form-control" name="description" id="description" cols="30" rows="10">{{accountbook.description}}</textarea>
    </div>
    <div class="container-fluid d-flex justify-content-between">
        <button type="submit" class="btn btn-outline-primary" id="submit-button">수정</button> 
        <a href="{% url 'accountbooks:detail' accountbook.pk %}" class="btn btn-outline-primary justify-align-center" role="button" style="width: 13rem;">뒤로가기</a>
    </div>
</form>
</main>
</div>

<script>
    function validDate() {
        const dateInput = document.getElementsByname('date')[0];
        const submitButton = document.getElementsById('submit-button');
        if (!Date.parse(dateInput.value)) {
            submitButton.disabled = true;
        }   else {
            submitbutton.disabled = false;
        }
    }

</script>
{% endblock content %}

Django/Project/PJ_1/accountbooks/templates/accountbooks/index.html
{% extends 'accountbooks/base.html' %}

{% block content %}
<header>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid d-flex justify-content-around">
    <h1 class="navbar-brand">가계부 목록</h1>
    <a href="{% url 'accountbooks:new' %}" class="btn btn-outline-primary" role="button">가계부 생성</a>
    </div>
</nav>
</header>
<main>
<div class="container-fluid d-flex flex-column ms-5">
{% for accountbook in accountbooks %}
    <ul>
        <li><a href="{% url 'accountbooks:detail' accountbook.pk %}">{{ accountbook.pk }} - {{ accountbook.note }}</a> </li>
    </ul>
{% endfor %}
</div>
</main>

{% endblock content %}

Django/Project/PJ_1/accountbooks/templates/accountbooks/new.html
{% extends 'accountbooks/base.html' %}

{% block content %}
<div class="container mt-5">
<form action="{% url 'accountbooks:create' %}" method="POST">
    {% csrf_token %}
        <h1>New &#x26A1;</h1>
        <div class="input-group input-group-sm mb-3">
            <span class="input-group-text" id="inputGroup-sizing-sm" style="background-color: lightgoldenrodyellow;"> 내용 </span>
            <input type="text" name='note' id='note' class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-sm">
        </div>
        <div class="input-group input-group-sm mb-3">
            <span class="input-group-text" id="inputGroup-sizing-sm" style="background-color: lightgoldenrodyellow;"> 분류 </span>
            <input type="text" name='category' id='category' class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-sm">
        </div>
        <div class="input-group input-group-sm mb-3">
            <span class="input-group-text" id="inputGroup-sizing-sm" style="background-color: lightgoldenrodyellow;"> 사용금액 </span>
            <input type="amount" name='amount' id='amount' class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-sm">
        </div>
        <div class="input-group input-group-sm mb-3">
            <span class="input-group-text" id="inputGroup-sizing-sm" style="background-color: lightgoldenrodyellow;"> 사용날짜 </span>
            <input type="date" name='date' id='date' class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-sm" onchange="validDate" required>
        </div>
        <div class="input-group input-group-sm mb-3">
            <span class="input-group-text" id="inputGroup-sizing-sm" style="background-color: lightgoldenrodyellow;">메모 </span>
            <textarea name='description' id='description' class="form-control" cols="30" rows="10"></textarea>
        </div>

        <div class="container-fluid d-flex justify-content-around mt-3">
            
            <button type="submit" class="btn btn-outline-primary" id="submit-button">생성</button>
            <a href="{% url 'accountbooks:index'%}" class="btn btn-outline-primary justify-align-center" role="button">뒤로가기</a>
        </div>

</form>
<script>
    function validDate() {
        const dateInput = document.getElementsByname('date')[0];
        const submitButton = document.getElementsById('submit-button');
        if (!Date.parse(dateInput.value)) {
            submitButton.disabled = true;
        }   else {
            submitbutton.disabled = false;
        }
    }

</script>

{% endblock content %}
