Django/z. Skeleton file/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('profile/<user_pk>/', views.profile, name='profile'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
]

Django/z. Skeleton file/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('reviews/', include('reviews.urls')),
    path('accounts/', include('accounts.urls')),
]

Django/z. Skeleton file/reviews/urls.py
from django.urls import path
from . import views

app_name = 'reviews'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:review_pk>/', views.detail, name='detail'),
    path('<int:review_pk>/comments/', views.comment_create, name='comment_create'),
    path(
        '<int:review_pk>/comments/<int:comment_pk>/delete/',
        views.comment_delete,
        name='comment_delete',
    ),
]

Django/z. Skeleton file/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

Django/z. Skeleton file/reviews/models.py
from django.db import models


class Review(models.Model):
    title = models.CharField(max_length=80)
    content = models.TextField(null=False)
    movie = models.CharField(max_length=80)


class Comment(models.Model):
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    content = models.TextField(null=False)

Django/z. Skeleton file/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = (
            'username',
            'email',
            'first_name',
            'last_name',
            'password1',
            'password2',
        )

Django/z. Skeleton file/reviews/forms.py
from django import forms
from .models import Review, Comment


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = '__all__'


class CommentForm(forms.ModelForm):
    content = forms.CharField(widget=forms.TextInput())

    class Meta:
        model = Comment
        fields = ('content',)

Django/z. Skeleton file/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import get_user_model
from .forms import CustomUserCreationForm


@login_required
def profile(request, user_pk):
    user = get_user_model().objects.get(pk=user_pk)

    context = {
        'user': user,
    }

    return render(request, 'accounts/profile.html', context)


def login(request):
    if request.user.is_authenticated:
        return redirect('reviews:index')

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('reviews:index')
    else:
        form = AuthenticationForm()

    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)
    return redirect('reviews:index')


def signup(request):
    if request.user.is_authenticated:
        return redirect('reviews:index')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('reviews:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)

Django/z. Skeleton file/reviews/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_safe
from .models import Review, Comment
from .forms import ReviewForm, CommentForm


def index(request):
    reviews = Review.objects.order_by('-pk')
    context = {
        'reviews': reviews,
    }
    return render(request, 'reviews/index.html', context)


def detail(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    comments = review.comment_set.all()
    comment_form = CommentForm()
    context = {
        'review': review,
        'comments': comments,
        'comment_form': comment_form,
    }
    return render(request, 'reviews/detail.html', context)


def create(request):
    if request.method == "POST":
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save()
            return redirect('reviews:detail', review_pk=review.pk)

    else:
        form = ReviewForm()

    context = {
        'form': form,
    }

    return render(request, 'reviews/create.html', context)


def comment_create(request, review_pk):
    if request.method == "POST":
        review = Review.objects.get(pk=review_pk)
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.review = review
            comment.save()
        return redirect('reviews:detail', review.pk)


def comment_delete(request, review_pk, comment_pk):
    if request.method == "POST":
        comment = Comment.objects.get(pk=comment_pk)
        comment.delete()
    return redirect('reviews:detail', review_pk)

Django/z. Skeleton file/reviews/templates/reviews/create.html
{% extends "base.html" %}
{% block content %}
  <h3>CREATE</h3>
  <form action="{% url 'reviews:create' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="글 작성"></input>
  </form>
{% endblock content %}

Django/z. Skeleton file/reviews/templates/reviews/detail.html
{% extends "base.html" %}
{% block content %}
  <h3>DETAIL</h3>
  <p>
    후기 번호 -
    {{review.pk}}
  </p>
  <p>
    후기 제목 -
    {{review.title}}
  </p>
  <p>
    후기 내용 -
    {{review.content}}
  </p>
  <p>
    영화 이름 -
    {{review.movie}}
  </p>
  <a href="{% url 'reviews:index' %}">[back]</a>
  <hr>
  <form action="{% url 'reviews:comment_create' review.pk %}" method="post">
    {% csrf_token %}
    {{ comment_form.as_p }}
    <input type="submit" value="댓글 작성">
  </form>
  <hr>
  <h3>
    댓글 목록
  </h3>
  {% for comment in comments %}
    <div>
      <p>댓글 번호 -
        {{ comment.pk }}</p>
      <p>
        댓글 내용 -
        {{comment.content}}
      </p>
      <form action="{% url 'reviews:comment_delete' review.pk comment.pk %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="댓글 삭제">
      </form>
    </div>
    <hr>
  {% endfor %}
{% endblock content %}

Django/z. Skeleton file/reviews/templates/reviews/index.html
{% extends "base.html" %}
{% block content %}
  <div>
    <h3>
      {{ user }}
      님 안녕하세요!
    </h3>
    {% if request.user.is_authenticated %}
      <div>
        <form action="{% url 'accounts:logout' %}" method="POST" class="">
          {% csrf_token %}
          <input type="submit" value="로그아웃" autocomplete="off">
        </form>
        <a href="{% url 'reviews:create' %}">[후기 작성]</a>
      </div>
    {% else %}
      <div>
        <a href="{% url 'accounts:login' %} ">[로그인]</a>
        <a href="{% url 'accounts:signup' %} ">[회원가입]</a>
      </div>
    {% endif %}

  </div>
  {% for review in reviews %}
    <p>
      <p>후기 번호 -
        {{ review.pk }}
      </p>
      <p>
        영화 이름 -
        {{review.movie}}
      </p>
    </p>
    <a href="{% url 'reviews:detail' review.pk %}">[detail]</a>
    <hr>
  {% endfor %}
{% endblock content %}