Django/Project/PJ_2/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('mypage/', views.mypage, name='mypage'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('password/', views.change_password, name='change_password'),

]

Django/Project/PJ_2/pjt7/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
]

Django/Project/PJ_2/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'), # 전체 글 띄우기
    path('create/', views.create, name='create'), # 글 작성(전체 글로 리다이렉트)
    path('<int:pk>/', views.detail, name='detail'), # 상세 조회(삭제, 수정 버튼)
    path('<int:pk>/delete/', views.delete, name='delete'), # 게시글 삭제
    path('<int:pk>/update/', views.update, name='update'), # 게시글 수정
    path('category/<str:subject>/', views.category, name='category'), # 게시글 분류
]

Django/Project/PJ_2/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>IT_CAT</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
    <link rel="shortcut icon" type="image/x-icon" href="https://cdn-icons-png.flaticon.com/512/4201/4201220.png">
  </head>
    <style>
      @font-face {
        font-family: 'NeoDunggeunmoPro-Regular';
        src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2302@1.0/NeoDunggeunmoPro-Regular.woff2') format('woff2');
        font-weight: normal;
        font-style: normal;
      }
      @font-face {
        font-family: 'TheJamsil5Bold';
        src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2302_01@1.0/TheJamsil5Bold.woff2') format('woff2');
        font-weight: 700;
        font-style: normal;
      }

      .main_height {
        height : 60rem
      }
    </style>
    {% block style %}
    {% endblock style %}
  <body>
    <div class="container-fluid">
      <!--navbar-->
      <nav class="navbar bg-body-tertiary sticky-top">
        <div class="my-auto">
          <a class="navbar-brand" href="#">
            <a class="text-decoration-none" style="font-family: 'NeoDunggeunmoPro-Regular'; font-size: 24px;" href="{% url 'index' %}">
              <span class="material-symbols-outlined">computer</span>IT_Info
            </a>
          </a>
        </div>

        <div class="d-grid gap-2 d-flex ">
          <div class="row d-flex ">
            {% if request.user.is_authenticated %}
            <div class="d-flex">
              <p class="my-auto text-nowrap mx-3">{{ user }}님, 안녕하세요!</p>
              <div class="btn-group dropstart">
                <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                메뉴 버튼
                </button>
                <ul class="dropdown-menu">
                  <li><a id="mypage" class="btn btn-outline-info btn-sm border-0 form-control rounded-end" href="{% url 'accounts:mypage' %}" >Mypage</a></li>
                  <li>
                    <form class="my-auto" action="{% url 'accounts:logout' %}" method="POST">
                      {% csrf_token %}
                      <input class="btn btn-outline-danger btn-sm border-0 form-control" type="submit" value="Logout" id="logout">
                    </form>
                  </li>
              </div>
            </div> 

            {% else %}
            <div class="btn-group dropstart">
              <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
              메뉴 버튼
              </button>
              <ul class="dropdown-menu">
                <li>
                <a href="{% url 'accounts:signup' %}" class="btn btn-outline-danger btn-sm border-0 form-control rounded-end">회원가입</a>
                </li>
                <li>
                <a href="{% url 'accounts:login' %}" class="btn btn-outline-primary btn-sm border-0 form-control rounded-end">로그인</a>
                </li>
              </ul>
            {% endif %}
            </div>
          </div>
        </div>
      </nav>
      
      <div class="container main_height">
        <div class="row">
          <div class="col-3 border-end">
            <h1 class="my-3 mx-2" style="font-family: 'TheJamsil5Bold';">IT 정보 공유</h1>
            <hr>
            <ul class="list-unstyled fs-3 list-group">
              {% if request.user.is_authenticated %}
              <li class="list-group-item d-flex justify-content-between align-items-center">
                <a class="text-decoration-none link-danger" href="{% url 'posts:create' %}" style="font-family: 'NeoDunggeunmoPro-Regular';">글 작성</a>
              </li>
              {% endif %}
              <li class="list-group-item d-flex justify-content-between align-items-center">
                <a class="text-decoration-none link-dark" href="{% url 'posts:index' %}" style="font-family: 'NeoDunggeunmoPro-Regular';">모든 글</a>
                <span class="badge bg-primary rounded-pill">{% block c1 %}{% endblock c1 %}</span>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
                <a class="text-decoration-none link-dark" href="{% url 'posts:category' '개발' %}" style="font-family: 'NeoDunggeunmoPro-Regular';">개발</a>
                  <span class="badge bg-primary rounded-pill">{% block c2 %}{% endblock c2 %}</span>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
                <a class="text-decoration-none link-dark" href="{% url 'posts:category' 'CS' %}" style="font-family: 'NeoDunggeunmoPro-Regular';">CS</a>
                  <span class="badge bg-primary rounded-pill">{% block c3 %}{% endblock c3 %}</span>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
                <a class="text-decoration-none link-dark" href="{% url 'posts:category' '신기술' %}" style="font-family: 'NeoDunggeunmoPro-Regular';">신기술</a>
                  <span class="badge bg-primary rounded-pill">{% block c4 %}{% endblock c4 %}</span>
              </li>
            </ul>
          </div>
          <div class="col-9">
            {% block content %}
            {% endblock content %}
          </div>
        </div>
      </div>

    <footer class="container text-body-secondary justify-content-center">
      <div class="d-flex justify-content-evenly">
        <span class="m-1 fs-6 fw-normal text-nowrap">IT Info</span>
        <span class="m-1 fs-6 fw-normal text-nowrap">소개</span>
        <span class="m-1 fs-6 fw-normal text-nowrap">API</span>
        <span class="m-1 fs-6 fw-normal text-nowrap">인기 계정</span>
        <span class="m-1 fs-6 fw-normal text-nowrap">위치</span>
        <span class="m-1 fs-6 fw-normal text-nowrap">Cat Lite</span>
        <span class="m-1 fs-6 fw-normal text-nowrap">연락처 업로드 & 비사용자</span>
        <span class="m-1 fs-6 fw-normal text-nowrap">Cat Verified</span>
      </div>
      <div class="d-flex justify-content-center">
        <div class="dropdown d-inline-block m-3">
          <a class="dropdown-toggle text-decoration-none text-body-secondary" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            팀원 명단
          </a>
          <ul class="dropdown-menu text-center">
            <li><a class="dropdown-item" href="https://github.com/jangjaeyong1115">장재용</a></li>
            <li><a class="dropdown-item" href="https://github.com/Pysonny">최계수</a></li>
            <li><a class="dropdown-item" href="https://github.com/hany0147">장하늬</a></li>
          </ul>
        </div>
        <span class="m-3">© 2023 Cat from Team19</span>
      </div>
    </footer>
      
  </div>    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </body>
</html>

Django/Project/PJ_2/templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="m-5 d-flex flex-column align-items-center">
<div>
  <img class="" src="https://d1bg8rd1h4dvdb.cloudfront.net/upload/imgServer/storypick/editor/2019090315083012205.jpg" alt="">
</div>
  <h3 class="mt-3 text-center" style="font-family: 'NeoDunggeunmoPro-Regular';">반갑다냥! IT정보 가져가라냥!</h3>
</div>
{% endblock content %}
{% block c1 %}
  {{ all_count }}
{% endblock c1 %}
{% block c2 %}
  {{ dev_count }}
{% endblock c2 %}
{% block c3 %}
  {{ cs_count }}
{% endblock c3 %}
{% block c4 %}
  {{ newT_count }}
{% endblock c4 %}